# Generated by Django 4.2.23 on 2025-08-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_teacher_newregester_role_alter_newregester_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('regnum', models.CharField(max_length=20, unique=True)),
                ('sec', models.CharField(max_length=100)),
            ],
        ),
    ]
